### ISSUE TITLE
About the core code for the RCL loss.

### ISSUE THREAD

**Issue by polaris-973** [skynbe/FedRCL#2]
First, I would like to thank the authors for their open source work. And can you provide the core code for the RCL loss? Or indicate exactly where it is in the repository, as I didn't find where the core code is after skimming.

**Comment by skynbe** [comment]
Thanks for your interest. We just refactored some things for easier understanding.

1. [RCLClient](https://github.com/skynbe/FedRCL/blob/main/clients/rcl_client.py) manages client-side operations for FedRCL traning.
2. [CLLoss](https://github.com/skynbe/FedRCL/blob/7748b85f6995b5a6ca0fd425cd4b195f8b2003f9/utils/loss.py#L56) is the implementation of contrastive learning loss. We implement RCL loss by a summation of SCL loss and divergence penalty loss as in [here](https://github.com/skynbe/FedRCL/blob/7748b85f6995b5a6ca0fd425cd4b195f8b2003f9/clients/rcl_client.py#L38), each of which is a variant of CL loss.
3. [fedrcl.yaml](https://github.com/skynbe/FedRCL/blob/main/configs/client/fedrcl.yaml) shows the detailed configurations of RCL Loss. You can directly change the values here, or can create the new yaml files.

We will update the README file soon as well.
