### ISSUE TITLE
The use of topk_pos and topk_neg

### ISSUE THREAD

**Issue by dylan981001** [skynbe/FedRCL#3]
Hi,
Thanks for this sharing your amazing work. I'm confused about the use of topk_pos and topk_neg. Based on the expression in the paper, I thought I was supposed to calculate all positive and negative pairs for a given data sample. However, the code seems to have used only some of the pairs, using topk_pos (default: 1) and topk_neg (default: 2). I would like to ask if it is still possible to calculate all positive and negative pairs by performing the training in this way.
Best,
Kim

**Comment by skynbe** [comment]
Hi, we select the most challenging positive and negative samples from the available pairs (based on similarity scores). This hard negative/positive sampling strategy is a widely adopted technique for enhancing the effectiveness of contrastive training (https://arxiv.org/pdf/2010.04592).

**Comment by dylan981001** [comment]
Thank you for your reply.
